
[[constraint]]
  name = "github.com/onsi/ginkgo"

[[constraint]]
  name = "github.com/onsi/gomega"

[[constraint]]
  name = "code.cloudfoundry.org/credhub-cli"
  version = "2.0.0"

[[constraint]]
  name = "code.cloudfoundry.org/routing-api"
